config-version: 2
name: 'mailchimp'
version: '1.0.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  mailchimp:
    +schema: mailchimp
    +materialized: table
    intermediate:
      +materialized: ephemeral
    staging:
      +materialized: table
      +schema: stg_mailchimp
      tmp:
        +materialized: view

vars:
  mailchimp:
    automation: "{{ source('mailchimp','automation') }}"
    automation_email: "{{ source('mailchimp','automation_email') }}"
    automation_recipient: "{{ source('mailchimp','automation_recipient') }}"
    automation_recipient_activity: "{{ source('mailchimp','automation_recipient_activity') }}"
    campaign: "{{ source('mailchimp','campaign') }}"
    campaign_recipient: "{{ source('mailchimp','campaign_recipient') }}"
    campaign_recipient_activity: "{{ source('mailchimp','campaign_recipient_activity') }}"
    mailchimp_segment: "{{ source('mailchimp','segment') }}"
    segment_member: "{{ source('mailchimp','segment_member') }}"
    list: "{{ source('mailchimp','list') }}"
    member: "{{ source('mailchimp','member') }}"
    unsubscribe: "{{ source('mailchimp','unsubscribe') }}"
    mailchimp__members_pass_through_columns: []
