config-version: 2
name: 'mailchimp'
version: '1.0.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  mailchimp:
    +schema: mailchimp
    +materialized: table
    intermediate:
      +materialized: ephemeral
    staging:
      +materialized: table
      +schema: stg_mailchimp
      tmp:
        +materialized: view
vars:
  automation: "{{ source('mailchimp', 'automations') }}"
  automation_email: "{{ source('mailchimp', 'automation_emails') }}"
  automation_recipient: "{{ source('mailchimp', 'automation_recipients') }}"
  automation_recipient_activity: "{{ source('mailchimp', 'automation_activities') }}"
  campaign: "{{ source('mailchimp', 'campaigns') }}"
  campaign_recipient: "{{ source('mailchimp', 'campaign_recipients') }}"
  campaign_recipient_activity: "{{ ref('stg_mailchimp_campaign_activities') }}"
  mailchimp_segment: "{{ source('mailchimp', 'segments') }}"
  segment_member: "{{ source('mailchimp', 'segment_members') }}"
  list: "{{ source('mailchimp', 'lists') }}"
  member: "{{ source('mailchimp', 'members') }}"
  unsubscribe: "{{ source('mailchimp', 'unsubscribes') }}"
  mailchimp__members_pass_through_columns: []
