config-version: 2
name: 'mailchimp_integration_tests'
version: '0.11.0'
profile: 'integration_tests'

models:
  +schema: "mailchimp_{{ var('directed_schema','dev') }}"

vars:
  mailchimp_source:
    mailchimp_schema: mailchimp_integration_tests_2
    mailchimp_automation_identifier: "automation"
    mailchimp_automation_email_identifier: "automation_email"
    mailchimp_automation_recipient_identifier: "automation_recipient"
    mailchimp_automation_recipient_activity_identifier: "automation_recipient_activity"
    mailchimp_campaign_identifier: "campaign"
    mailchimp_campaign_recipient_identifier: "campaign_recipient"
    mailchimp_campaign_recipient_activity_identifier: "campaign_recipient_activity"
    mailchimp_mailchimp_segment_identifier: "segment"
    mailchimp_segment_member_identifier: "segment_member"
    mailchimp_list_identifier: "list"
    mailchimp_member_identifier: "member"
    mailchimp_unsubscribe_identifier: "unsubscribe"
  mailchimp:
    automation: "{{ ref('stg_mailchimp__automations') }}"
    automation_email: "{{ ref('stg_mailchimp__automation_emails') }}"
    automation_recipient: "{{ ref('stg_mailchimp__automation_recipients') }}"
    automation_recipient_activity: "{{ ref('stg_mailchimp__automation_activities') }}"
    campaign: "{{ ref('stg_mailchimp__campaigns') }}"
    campaign_recipient: "{{ ref('stg_mailchimp__campaign_recipients') }}"
    campaign_recipient_activity: "{{ ref('stg_mailchimp_campaign_activities') }}"
    mailchimp_segment: "{{ ref('stg_mailchimp__segments') }}"
    segment_member: "{{ ref('stg_mailchimp__segment_members') }}"
    list: "{{ ref('stg_mailchimp__lists') }}"
    member: "{{ ref('stg_mailchimp__members') }}"
    unsubscribe: "{{ ref('stg_mailchimp__unsubscribes') }}"
    mailchimp_using_automations: true
    mailchimp_using_segments: true
seeds:
  mailchimp_integration_tests:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    +column_types:
      _fivetran_synced: timestamp
    automation:
      +column_types:
        create_time: timestamp
        start_time: timestamp
    automation_email:
      +column_types:
        create_time: timestamp
        start_time: timestamp
        send_time: timestamp
    automation_recipient_activity:
      +column_types:
        timestamp: timestamp
    campaign:
      +column_types:
        create_time: timestamp
        send_time: timestamp
    campaign_recipient_activity:
      +column_types:
        timestamp: timestamp
    list:
      +column_types:
        list_rating: float
        date_created: timestamp
    member:
      +column_types:
        dstoff: float
        gmtoff: float
        last_changed: timestamp
        timestamp_opt: timestamp
        timestamp_signup: timestamp
    segment:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
    unsubscribe:
      +column_types:
        timestamp: timestamp

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']