name: 'generate dbt docs'
on:
  pull_request:
    types:
      - labeled

jobs:
  generate-docs:
    if: github.event.label.name == 'docs:ready'
    uses: fivetran/dbt_package_automations/.github/workflows/generate-docs.yml@feature/generate-docs
    with:
      schema_var_name: mailchimp_schema